//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Метаданные связи EDM

[assembly: EdmRelationshipAttribute("VodocanalModel", "FK__Employeer__id_po__534D60F1", "Posts", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PRACT_LAB_1_EF.Posts), "Employeers", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PRACT_LAB_1_EF.Employeers), true)]

#endregion

namespace PRACT_LAB_1_EF
{
    #region Контексты
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    public partial class VodocanalEntities2 : ObjectContext
    {
        #region Конструкторы
    
        /// <summary>
        /// Инициализирует новый объект VodocanalEntities2, используя строку соединения из раздела "VodocanalEntities2" файла конфигурации приложения.
        /// </summary>
        public VodocanalEntities2() : base("name=VodocanalEntities2", "VodocanalEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Инициализация нового объекта VodocanalEntities2.
        /// </summary>
        public VodocanalEntities2(string connectionString) : base(connectionString, "VodocanalEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Инициализация нового объекта VodocanalEntities2.
        /// </summary>
        public VodocanalEntities2(EntityConnection connection) : base(connection, "VodocanalEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Разделяемые методы
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Свойства ObjectSet
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<Employeers> Employeers
        {
            get
            {
                if ((_Employeers == null))
                {
                    _Employeers = base.CreateObjectSet<Employeers>("Employeers");
                }
                return _Employeers;
            }
        }
        private ObjectSet<Employeers> _Employeers;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<Posts> Posts
        {
            get
            {
                if ((_Posts == null))
                {
                    _Posts = base.CreateObjectSet<Posts>("Posts");
                }
                return _Posts;
            }
        }
        private ObjectSet<Posts> _Posts;

        #endregion

        #region Методы AddTo
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet Employeers. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToEmployeers(Employeers employeers)
        {
            base.AddObject("Employeers", employeers);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet Posts. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToPosts(Posts posts)
        {
            base.AddObject("Posts", posts);
        }

        #endregion

    }

    #endregion

    #region Сущности
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VodocanalModel", Name="Employeers")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Employeers : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта Employeers.
        /// </summary>
        /// <param name="employeer_id">Исходное значение свойства employeer_id.</param>
        /// <param name="employeer_name">Исходное значение свойства employeer_name.</param>
        /// <param name="employeer_surname">Исходное значение свойства employeer_surname.</param>
        /// <param name="id_post">Исходное значение свойства id_post.</param>
        public static Employeers CreateEmployeers(global::System.Int32 employeer_id, global::System.String employeer_name, global::System.String employeer_surname, global::System.Int32 id_post)
        {
            Employeers employeers = new Employeers();
            employeers.employeer_id = employeer_id;
            employeers.employeer_name = employeer_name;
            employeers.employeer_surname = employeer_surname;
            employeers.id_post = id_post;
            return employeers;
        }

        #endregion

        #region Простые свойства
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 employeer_id
        {
            get
            {
                return _employeer_id;
            }
            set
            {
                if (_employeer_id != value)
                {
                    Onemployeer_idChanging(value);
                    ReportPropertyChanging("employeer_id");
                    _employeer_id = StructuralObject.SetValidValue(value, "employeer_id");
                    ReportPropertyChanged("employeer_id");
                    Onemployeer_idChanged();
                }
            }
        }
        private global::System.Int32 _employeer_id;
        partial void Onemployeer_idChanging(global::System.Int32 value);
        partial void Onemployeer_idChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String employeer_name
        {
            get
            {
                return _employeer_name;
            }
            set
            {
                Onemployeer_nameChanging(value);
                ReportPropertyChanging("employeer_name");
                _employeer_name = StructuralObject.SetValidValue(value, false, "employeer_name");
                ReportPropertyChanged("employeer_name");
                Onemployeer_nameChanged();
            }
        }
        private global::System.String _employeer_name;
        partial void Onemployeer_nameChanging(global::System.String value);
        partial void Onemployeer_nameChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String employeer_surname
        {
            get
            {
                return _employeer_surname;
            }
            set
            {
                Onemployeer_surnameChanging(value);
                ReportPropertyChanging("employeer_surname");
                _employeer_surname = StructuralObject.SetValidValue(value, false, "employeer_surname");
                ReportPropertyChanged("employeer_surname");
                Onemployeer_surnameChanged();
            }
        }
        private global::System.String _employeer_surname;
        partial void Onemployeer_surnameChanging(global::System.String value);
        partial void Onemployeer_surnameChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String employeer_middlename
        {
            get
            {
                return _employeer_middlename;
            }
            set
            {
                Onemployeer_middlenameChanging(value);
                ReportPropertyChanging("employeer_middlename");
                _employeer_middlename = StructuralObject.SetValidValue(value, true, "employeer_middlename");
                ReportPropertyChanged("employeer_middlename");
                Onemployeer_middlenameChanged();
            }
        }
        private global::System.String _employeer_middlename;
        partial void Onemployeer_middlenameChanging(global::System.String value);
        partial void Onemployeer_middlenameChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_post
        {
            get
            {
                return _id_post;
            }
            set
            {
                Onid_postChanging(value);
                ReportPropertyChanging("id_post");
                _id_post = StructuralObject.SetValidValue(value, "id_post");
                ReportPropertyChanged("id_post");
                Onid_postChanged();
            }
        }
        private global::System.Int32 _id_post;
        partial void Onid_postChanging(global::System.Int32 value);
        partial void Onid_postChanged();

        #endregion

        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VodocanalModel", "FK__Employeer__id_po__534D60F1", "Posts")]
        public Posts Posts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Posts>("VodocanalModel.FK__Employeer__id_po__534D60F1", "Posts").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Posts>("VodocanalModel.FK__Employeer__id_po__534D60F1", "Posts").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Posts> PostsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Posts>("VodocanalModel.FK__Employeer__id_po__534D60F1", "Posts");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Posts>("VodocanalModel.FK__Employeer__id_po__534D60F1", "Posts", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VodocanalModel", Name="Posts")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Posts : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта Posts.
        /// </summary>
        /// <param name="post_id">Исходное значение свойства post_id.</param>
        /// <param name="post_name">Исходное значение свойства post_name.</param>
        /// <param name="post_salary">Исходное значение свойства post_salary.</param>
        public static Posts CreatePosts(global::System.Int32 post_id, global::System.String post_name, global::System.Single post_salary)
        {
            Posts posts = new Posts();
            posts.post_id = post_id;
            posts.post_name = post_name;
            posts.post_salary = post_salary;
            return posts;
        }

        #endregion

        #region Простые свойства
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 post_id
        {
            get
            {
                return _post_id;
            }
            set
            {
                if (_post_id != value)
                {
                    Onpost_idChanging(value);
                    ReportPropertyChanging("post_id");
                    _post_id = StructuralObject.SetValidValue(value, "post_id");
                    ReportPropertyChanged("post_id");
                    Onpost_idChanged();
                }
            }
        }
        private global::System.Int32 _post_id;
        partial void Onpost_idChanging(global::System.Int32 value);
        partial void Onpost_idChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String post_name
        {
            get
            {
                return _post_name;
            }
            set
            {
                Onpost_nameChanging(value);
                ReportPropertyChanging("post_name");
                _post_name = StructuralObject.SetValidValue(value, false, "post_name");
                ReportPropertyChanged("post_name");
                Onpost_nameChanged();
            }
        }
        private global::System.String _post_name;
        partial void Onpost_nameChanging(global::System.String value);
        partial void Onpost_nameChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single post_salary
        {
            get
            {
                return _post_salary;
            }
            set
            {
                Onpost_salaryChanging(value);
                ReportPropertyChanging("post_salary");
                _post_salary = StructuralObject.SetValidValue(value, "post_salary");
                ReportPropertyChanged("post_salary");
                Onpost_salaryChanged();
            }
        }
        private global::System.Single _post_salary;
        partial void Onpost_salaryChanging(global::System.Single value);
        partial void Onpost_salaryChanged();

        #endregion

        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VodocanalModel", "FK__Employeer__id_po__534D60F1", "Employeers")]
        public EntityCollection<Employeers> Employeers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Employeers>("VodocanalModel.FK__Employeer__id_po__534D60F1", "Employeers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Employeers>("VodocanalModel.FK__Employeer__id_po__534D60F1", "Employeers", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
